### ISSUE TITLE
iCal not supporting UTC

### ISSUE THREAD

**Issue by TotalKrill** [cryptocrack/calcurse#3]
The iCal functionality does not support UTC enabled ics documents. Google uses theese and this messes up the time for different things. would be awesome to be able to manually fix this with maybe an --utc +/-hour flag to the cli commands. Thank you!

**Comment by cryptocrack** [comment]
Sorry, this took quite look. Parsing UTC times should work now, though.

**Comment by TotalKrill** [comment]
Great! Ty!
